//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiamGia
    {
        public string MaGiamGia { get; set; }
        public string TenMaGiamGia { get; set; }
        public Nullable<double> GiaTri { get; set; }
        public string Active { get; set; }
    }
}
