//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public string MaPN { get; set; }
        public string MaNCC { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string DaXoa { get; set; }
    
        public virtual ChiTietPhieuNhap ChiTietPhieuNhap { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
